name: deploy-frontend-dev

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: goal-tracker-dev
  PROJECT_NAME: goal-tracker-dev
  PROJECT_REGION: europe-north1
  ARTIFACTS: frontend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
