name: deploy-frontend-dev

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: goal-tracker-dev
  PROJECT_NAME: goal-tracker-dev
  PROJECT_REGION: europe-north1
  ARTIFACTS: frontend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Lint frontend
        run: |
          cd frontend
          npm run tidy

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Test frontend
        run: |
          cd frontend
          npm test

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Lint backend
        run: |
          cd backend
          npm run tidy

      - name: Test backend
        run: |
          cd backend
          npm test
